### ISSUE TITLE
letzter Stand

### ISSUE THREAD

**Issue by Monarch73** [angular-schule/2017-12-angular-workshop-neuss#1]
Hallo Johannes,

ich wäre dir dankbar, wenn du noch den letzten Stand hier hoch pushen könntest, wenn es keine zu großen Umstände macht. Die Beispiele mit dem router, sessionStorage und parameter scheinen noch zu fehlen.

Lieben Gruß,
Niels Hüsken

**Comment by JohannesHoppe** [comment]
Sorry, hatte zum Schluss vergessen zu pushen. @chris1302 hatte auch noch eine Frage zur Auth-Geschichte, da mache ich noch ein kleines  Beispiel in #2.

FYI @fmalcher

**Comment by Monarch73** [comment]
Besten Dank. Das hätte aber nicht zwangsweise heute sein müssen.

Einen schönen 3rd Advent wünsche ich allerseits...

**Comment by JohannesHoppe** [comment]
:rollin

**Comment by JohannesHoppe** [comment]
:innocent: Wochenende und Advent? Upsi!

Danke, ich wünsche ebenso einen besinnlichen Advent!
